# Application properties that need to be
# embedded within the web application can be included here
spring.main.banner-mode: OFF

#spring:
#  autoconfigure:
#    exclude:
#      - org.apereo.cas.oidc.config.OidcConfiguration